=== isheremetov/EpamLabXML/EpamLabXML/xml/knife.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="knife">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="weapon" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type" type="xs:string" />
							<xs:element name="handy" type="xs:string" />
							<xs:element name="origin" type="xs:string" />
							<xs:element name="visual">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="width" type="xs:int" />
										<xs:element name="height" type="xs:int" />
										<xs:element name="material" type="xs:string" />
										<xs:element name="handle">
											<xs:complexType>
												<xs:attribute name="material" use="required" />
												<xs:attribute name="kind" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="krovostok" type="xs:boolean" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="value" type="xs:boolean" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== isheremetov/EpamLabXML/EpamLabXML/xml/knife.xml
<?xml version="1.0" encoding="UTF-8"?>
<knife xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="knife.xsd">
  <weapon>
    <type>Нож</type>
    <handy>Одноручное</handy>
    <origin>Россия</origin>
    <visual>
      <width>20</width>
      <height>5</height>
      <material>Сталь</material>
      <handle kind="Дуб" material="Дерево"/>
      <krovostok>true</krovostok>
    </visual>
    <value>true</value>
  </weapon>
  <weapon>
    <type>Кинжал</type>
    <handy>Одноручное</handy>
    <origin>Белоруссия</origin>
    <visual>
      <width>30</width>
      <height>6</height>
      <material>Сталь</material>
      <handle material="Сталь"/>
      <krovostok>false</krovostok>
    </visual>
    <value>false</value>
  </weapon>
    <weapon>
    <type>Меч</type>
    <handy>Двуручное</handy>
    <origin>Россия</origin>
    <visual>
      <width>150</width>
      <height>10</height>
      <material>Сталь</material>
      <handle kind="Береза" material="Дерево"/>
      <krovostok>true</krovostok>
    </visual>
    <value>false</value>
  </weapon>
    <weapon>
    <type>Сабля</type>
    <handy>Одноручное</handy>
    <origin>Украина</origin>
    <visual>
      <width>60</width>
      <height>6</height>
      <material>Сталь</material>
      <handle material="Пластик"/>
      <krovostok>false</krovostok>
    </visual>
    <value>true</value>
  </weapon>
</knife>
